// Shared lint config for every app in the monorepo (apps/api now, apps/web later).
import { defineConfig } from 'eslint/config';
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettierRecommended from 'eslint-plugin-prettier/recommended';
import globals from 'globals';

export default defineConfig(
  {
    ignores: [
      '**/node_modules/',
      '**/dist/',
      '**/.next/',
      '**/coverage/',
      // Generated by Next.js on every build.
      '**/next-env.d.ts',
      // Read only by the Neon CLI, which brings its own @neon/config; it is not
      // part of any app, so no tsconfig covers it.
      'neon.ts',
    ],
  },
  js.configs.recommended,
  // Type-aware rules read each file's tsconfig, so they catch bugs plain lint can't,
  // e.g. a missing `await` inside a database transaction (no-floating-promises).
  tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        // Finds the nearest tsconfig.json for each file (apps/api now, apps/web later).
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  // Plain JavaScript files, like this config, have no types to check.
  {
    files: ['**/*.{js,mjs,cjs}'],
    extends: [tseslint.configs.disableTypeChecked],
  },
  // Formatting problems are reported as lint errors, so `npm run lint` checks both.
  prettierRecommended,
  {
    languageOptions: {
      globals: { ...globals.node, ...globals.jest },
    },
  },
);
