import { MigrationInterface, QueryRunner } from 'typeorm';

// The whole schema from docs/ERD.md: 5 enums, 5 tables, their CHECKs, indexes and
// foreign keys. Generated by `npm run migration:generate`, then edited by hand:
// - each shared enum (zone, request_status) is created once, not once per table;
// - ix_requests_passenger_history sorts created_at DESC (TypeORM can't express it);
// - statements are grouped by table in ERD order.
export class InitialSchema1790585110765 implements MigrationInterface {
  name = 'InitialSchema1790585110765';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // --- Enums (ERD §2) ---
    await queryRunner.query(
      `CREATE TYPE "public"."user_role" AS ENUM('PASSENGER', 'DRIVER')`,
    );
    await queryRunner.query(
      `CREATE TYPE "public"."zone" AS ENUM('BANANI', 'GULSHAN_1', 'MOHAKHALI', 'DHANMONDI', 'MIRPUR', 'UTTARA', 'FARMGATE', 'BASHUNDHARA')`,
    );
    await queryRunner.query(
      `CREATE TYPE "public"."pool_status" AS ENUM('MATCHED', 'DRIVER_ARRIVED', 'STARTED', 'COMPLETED', 'CANCELLED')`,
    );
    await queryRunner.query(
      `CREATE TYPE "public"."request_status" AS ENUM('REQUESTED', 'MATCHED', 'DRIVER_ARRIVED', 'STARTED', 'COMPLETED', 'CANCELLED')`,
    );
    await queryRunner.query(
      `CREATE TYPE "public"."event_type" AS ENUM('STATUS_CHANGED', 'FARE_CHANGED')`,
    );

    // --- users ---
    await queryRunner.query(`
      CREATE TABLE "users" (
        "id" uuid NOT NULL DEFAULT gen_random_uuid(),
        "name" character varying(80) NOT NULL,
        "email" character varying(255) NOT NULL,
        "password_hash" character varying(100) NOT NULL,
        "role" "public"."user_role" NOT NULL DEFAULT 'PASSENGER',
        "is_online" boolean NOT NULL DEFAULT false,
        "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "pk_users" PRIMARY KEY ("id")
      )`);
    await queryRunner.query(
      `CREATE UNIQUE INDEX "uq_users_email" ON "users" ("email")`,
    );

    // --- vehicles ---
    await queryRunner.query(`
      CREATE TABLE "vehicles" (
        "id" uuid NOT NULL DEFAULT gen_random_uuid(),
        "driver_id" uuid NOT NULL,
        "nickname" character varying(40) NOT NULL,
        "plate_number" character varying(20) NOT NULL,
        "capacity" smallint NOT NULL,
        "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "ck_vehicles_capacity" CHECK ("capacity" BETWEEN 1 AND 6),
        CONSTRAINT "pk_vehicles" PRIMARY KEY ("id")
      )`);
    await queryRunner.query(
      `CREATE UNIQUE INDEX "uq_vehicles_driver" ON "vehicles" ("driver_id")`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX "uq_vehicles_plate" ON "vehicles" ("plate_number")`,
    );

    // --- pools ---
    await queryRunner.query(`
      CREATE TABLE "pools" (
        "id" uuid NOT NULL DEFAULT gen_random_uuid(),
        "vehicle_id" uuid NOT NULL,
        "pickup_zone" "public"."zone" NOT NULL,
        "capacity" smallint NOT NULL,
        "seats_taken" smallint NOT NULL DEFAULT 0,
        "status" "public"."pool_status" NOT NULL DEFAULT 'MATCHED',
        "arrived_at" TIMESTAMP WITH TIME ZONE,
        "started_at" TIMESTAMP WITH TIME ZONE,
        "completed_at" TIMESTAMP WITH TIME ZONE,
        "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "ck_pools_seats" CHECK ("seats_taken" BETWEEN 0 AND "capacity"),
        CONSTRAINT "pk_pools" PRIMARY KEY ("id")
      )`);
    await queryRunner.query(`
      CREATE UNIQUE INDEX "uq_pools_active_vehicle" ON "pools" ("vehicle_id")
      WHERE "status" IN ('MATCHED', 'DRIVER_ARRIVED', 'STARTED')`);
    await queryRunner.query(
      `CREATE INDEX "ix_pools_open" ON "pools" ("pickup_zone", "status")`,
    );

    // --- ride_requests ---
    await queryRunner.query(`
      CREATE TABLE "ride_requests" (
        "id" uuid NOT NULL DEFAULT gen_random_uuid(),
        "passenger_id" uuid NOT NULL,
        "pool_id" uuid,
        "pickup_zone" "public"."zone" NOT NULL,
        "dropoff_zone" "public"."zone" NOT NULL,
        "seats" smallint NOT NULL,
        "distance_m" integer NOT NULL,
        "base_fare_paisa" integer NOT NULL,
        "distance_charge_paisa" integer NOT NULL,
        "pool_discount_paisa" integer NOT NULL DEFAULT 0,
        "fare_paisa" integer NOT NULL,
        "status" "public"."request_status" NOT NULL DEFAULT 'REQUESTED',
        "cancelled_at" TIMESTAMP WITH TIME ZONE,
        "completed_at" TIMESTAMP WITH TIME ZONE,
        "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "ck_ride_requests_zones" CHECK ("pickup_zone" <> "dropoff_zone"),
        CONSTRAINT "ck_ride_requests_seats" CHECK ("seats" BETWEEN 1 AND 3),
        CONSTRAINT "ck_ride_requests_distance" CHECK ("distance_m" > 0),
        CONSTRAINT "ck_ride_requests_fare_parts" CHECK ("base_fare_paisa" >= 0 AND "distance_charge_paisa" >= 0 AND "pool_discount_paisa" >= 0),
        CONSTRAINT "ck_ride_requests_fare" CHECK ("fare_paisa" = ("base_fare_paisa" + "distance_charge_paisa" - "pool_discount_paisa") * "seats"),
        CONSTRAINT "ck_ride_requests_pool" CHECK ("status" IN ('REQUESTED', 'CANCELLED') OR "pool_id" IS NOT NULL),
        CONSTRAINT "pk_ride_requests" PRIMARY KEY ("id")
      )`);
    await queryRunner.query(`
      CREATE UNIQUE INDEX "uq_requests_active_passenger" ON "ride_requests" ("passenger_id")
      WHERE "status" IN ('REQUESTED', 'MATCHED', 'DRIVER_ARRIVED', 'STARTED')`);
    await queryRunner.query(
      `CREATE INDEX "ix_requests_passenger_history" ON "ride_requests" ("passenger_id", "created_at" DESC)`,
    );
    await queryRunner.query(
      `CREATE INDEX "ix_requests_waiting" ON "ride_requests" ("status", "pickup_zone", "created_at")`,
    );
    await queryRunner.query(
      `CREATE INDEX "ix_requests_pool" ON "ride_requests" ("pool_id")`,
    );

    // --- ride_events (append-only history) ---
    await queryRunner.query(`
      CREATE TABLE "ride_events" (
        "id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
        "ride_request_id" uuid NOT NULL,
        "pool_id" uuid,
        "actor_id" uuid,
        "type" "public"."event_type" NOT NULL,
        "from_status" "public"."request_status",
        "to_status" "public"."request_status",
        "old_fare_paisa" integer,
        "new_fare_paisa" integer,
        "note" text,
        "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "pk_ride_events" PRIMARY KEY ("id")
      )`);
    await queryRunner.query(
      `CREATE INDEX "ix_events_request" ON "ride_events" ("ride_request_id", "id")`,
    );

    // --- Foreign keys: all ON DELETE RESTRICT, so history is never lost ---
    await queryRunner.query(
      `ALTER TABLE "vehicles" ADD CONSTRAINT "fk_vehicles_driver" FOREIGN KEY ("driver_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "pools" ADD CONSTRAINT "fk_pools_vehicle" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "ride_requests" ADD CONSTRAINT "fk_ride_requests_passenger" FOREIGN KEY ("passenger_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "ride_requests" ADD CONSTRAINT "fk_ride_requests_pool" FOREIGN KEY ("pool_id") REFERENCES "pools"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "ride_events" ADD CONSTRAINT "fk_ride_events_ride_request" FOREIGN KEY ("ride_request_id") REFERENCES "ride_requests"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "ride_events" ADD CONSTRAINT "fk_ride_events_pool" FOREIGN KEY ("pool_id") REFERENCES "pools"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "ride_events" ADD CONSTRAINT "fk_ride_events_actor" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`,
    );
  }

  // Undo in reverse order. Dropping a table also drops its indexes, CHECKs and
  // foreign keys; each enum is dropped once, after every table that uses it.
  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "ride_events"`);
    await queryRunner.query(`DROP TABLE "ride_requests"`);
    await queryRunner.query(`DROP TABLE "pools"`);
    await queryRunner.query(`DROP TABLE "vehicles"`);
    await queryRunner.query(`DROP TABLE "users"`);
    await queryRunner.query(`DROP TYPE "public"."event_type"`);
    await queryRunner.query(`DROP TYPE "public"."request_status"`);
    await queryRunner.query(`DROP TYPE "public"."pool_status"`);
    await queryRunner.query(`DROP TYPE "public"."zone"`);
    await queryRunner.query(`DROP TYPE "public"."user_role"`);
  }
}
